/**
 * POST /api/github/create-checklist-issues
 *
 * Creates GitHub issues from UI/UX checklist audit failures.
 * Each issue includes structured evidence for coding agents.
 */

import type { VercelRequest, VercelResponse } from "@vercel/node";

interface ChecklistIssueInput {
  repo: string; // "owner/repo"
  checkId: string;
  category: string;
  criterion: string;
  severity: "critical" | "high" | "medium" | "low";
  confidence: number;
  expected: string;
  observed: string;
  evidence: {
    source: string;
    page?: string;
    selector?: string;
    screenshotUrl?: string;
  };
  fixSuggestion: string;
  acceptanceCriteria: string[];
}

function formatIssueBody(input: ChecklistIssueInput): string {
  return `## UI/UX Checklist Failure

### Check
- **ID**: \`${input.checkId}\`
- **Category**: ${input.category}
- **Criterion**: ${input.criterion}
- **Severity**: ${input.severity}
- **Confidence**: ${(input.confidence * 100).toFixed(0)}%

### Expected
${input.expected}

### Observed
${input.observed}

### Evidence
- **Source**: ${input.evidence.source}
${input.evidence.page ? `- **Page**: ${input.evidence.page}` : ""}
${input.evidence.selector ? `- **Selector**: \`${input.evidence.selector}\`` : ""}
${input.evidence.screenshotUrl ? `- **Screenshot**: ${input.evidence.screenshotUrl}` : ""}

### Suggested Fix
${input.fixSuggestion}

### Acceptance Criteria
${input.acceptanceCriteria.map(c => `- [ ] ${c}`).join("\n")}

### Verification Commands
\`\`\`bash
npm run typecheck
npm run lint
npm test
npm run build
\`\`\`

---
*Auto-generated by Desygn AI Checklist Auditor*`;
}

function severityToLabels(severity: string): string[] {
  const labels = ["auto-generated", "checklist-failure"];
  if (severity === "critical" || severity === "high") {
    labels.push("high-priority");
  }
  return labels;
}

export default async function handler(req: VercelRequest, res: VercelResponse) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return res.status(500).json({ error: "GITHUB_TOKEN not configured" });
  }

  try {
    const issues: ChecklistIssueInput[] = Array.isArray(req.body) ? req.body : [req.body];

    const results = [];
    for (const issue of issues) {
      const [owner, repoName] = issue.repo.split("/");
      if (!owner || !repoName) {
        results.push({ checkId: issue.checkId, error: "Invalid repo format. Expected owner/repo" });
        continue;
      }

      const title = `[${issue.severity.toUpperCase()}] ${issue.category}: ${issue.criterion}`;
      const body = formatIssueBody(issue);
      const labels = severityToLabels(issue.severity);

      const response = await fetch(
        `https://api.github.com/repos/${owner}/${repoName}/issues`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
          },
          body: JSON.stringify({ title, body, labels }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        results.push({ checkId: issue.checkId, error: errorText });
        continue;
      }

      const data = await response.json();
      results.push({
        checkId: issue.checkId,
        issueNumber: data.number,
        issueUrl: data.html_url,
        status: "created",
      });
    }

    return res.status(200).json({ results });
  } catch (error) {
    return res.status(500).json({
      error: error instanceof Error ? error.message : "Unknown error",
    });
  }
}
