/**
 * POST /api/github/create-checklist-issues
 *
 * Creates GitHub issues from UI/UX checklist audit failures.
 * Each issue includes structured evidence for coding agents.
 */

import type { VercelRequest, VercelResponse } from "@vercel/node";
import { z } from "zod";
import { withRateLimit } from "../lib/rate-limit";
import { getAllowedOrigin, setCorsHeaders } from "../lib/cors";

// ---------------------------------------------------------------------------
// Zod schema
// ---------------------------------------------------------------------------

const EvidenceSchema = z.object({
  source: z.string().min(1, "evidence.source is required"),
  page: z.string().optional(),
  selector: z.string().optional(),
  screenshotUrl: z.string().url("evidence.screenshotUrl must be a valid URL").optional(),
});

const ChecklistIssueSchema = z.object({
  repo: z
    .string()
    .regex(/^[^/]+\/[^/]+$/, 'repo must be in "owner/repo" format'),
  checkId: z.string().min(1, "checkId is required"),
  category: z.string().min(1, "category is required"),
  criterion: z.string().min(1, "criterion is required"),
  severity: z.enum(["critical", "high", "medium", "low"]),
  confidence: z.number().min(0).max(1),
  expected: z.string().min(1, "expected is required"),
  observed: z.string().min(1, "observed is required"),
  evidence: EvidenceSchema,
  fixSuggestion: z.string().min(1, "fixSuggestion is required"),
  acceptanceCriteria: z.array(z.string()).min(1, "at least one acceptanceCriteria entry is required"),
});

const RequestBodySchema = z.union([
  ChecklistIssueSchema,
  z.array(ChecklistIssueSchema).min(1, "at least one issue is required"),
]);

type ChecklistIssueInput = z.infer<typeof ChecklistIssueSchema>;

function formatIssueBody(input: ChecklistIssueInput): string {
  return `## UI/UX Checklist Failure

### Check
- **ID**: \`${input.checkId}\`
- **Category**: ${input.category}
- **Criterion**: ${input.criterion}
- **Severity**: ${input.severity}
- **Confidence**: ${(input.confidence * 100).toFixed(0)}%

### Expected
${input.expected}

### Observed
${input.observed}

### Evidence
- **Source**: ${input.evidence.source}
${input.evidence.page ? `- **Page**: ${input.evidence.page}` : ""}
${input.evidence.selector ? `- **Selector**: \`${input.evidence.selector}\`` : ""}
${input.evidence.screenshotUrl ? `- **Screenshot**: ${input.evidence.screenshotUrl}` : ""}

### Suggested Fix
${input.fixSuggestion}

### Acceptance Criteria
${input.acceptanceCriteria.map(c => `- [ ] ${c}`).join("\n")}

### Verification Commands
\`\`\`bash
npm run typecheck
npm run lint
npm test
npm run build
\`\`\`

---
*Auto-generated by Desygn AI Checklist Auditor*`;
}

function severityToLabels(severity: string): string[] {
  const labels = ["auto-generated", "checklist-failure"];
  if (severity === "critical" || severity === "high") {
    labels.push("high-priority");
  }
  return labels;
}

// ---------------------------------------------------------------------------
// Retry helper with exponential backoff
// ---------------------------------------------------------------------------

async function fetchWithRetry(
  url: string,
  init: RequestInit,
  maxRetries = 2,
  baseDelayMs = 1000
): Promise<Response> {
  let lastError: unknown;
  for (let attempt = 0; attempt <= maxRetries; attempt++) {
    try {
      const response = await fetch(url, init);
      // Retry on GitHub 5xx transient errors only
      if (response.status >= 500 && attempt < maxRetries) {
        await new Promise((r) => setTimeout(r, baseDelayMs * Math.pow(2, attempt)));
        continue;
      }
      return response;
    } catch (err) {
      // Network-level error — retry
      lastError = err;
      if (attempt < maxRetries) {
        await new Promise((r) => setTimeout(r, baseDelayMs * Math.pow(2, attempt)));
      }
    }
  }
  throw lastError ?? new Error("GitHub API request failed after retries");
}

// ---------------------------------------------------------------------------
// Handler
// ---------------------------------------------------------------------------

async function handler(req: VercelRequest, res: VercelResponse) {
  // --- CORS headers (always set, including preflight) ---
  const origin = getAllowedOrigin(req);
  setCorsHeaders(res, origin);
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization, X-API-Key");
  res.setHeader("Content-Type", "application/json");

  if (req.method === "OPTIONS") {
    return res.status(204).end();
  }

  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  // --- GITHUB_TOKEN env check ---
  const token = process.env.GITHUB_TOKEN;
  if (!token) {
    return res.status(500).json({
      error: "GITHUB_TOKEN not configured",
      setup: "Set the GITHUB_TOKEN environment variable to a GitHub personal access token with 'repo' scope.",
    });
  }

  // --- Auth validation (Bearer or X-API-Key) ---
  const authHeader = req.headers["authorization"];
  const apiKeyHeader = req.headers["x-api-key"];
  const hasBearer =
    typeof authHeader === "string" && authHeader.toLowerCase().startsWith("bearer ");
  const hasApiKey = typeof apiKeyHeader === "string" && apiKeyHeader.length > 0;

  if (!hasBearer && !hasApiKey) {
    return res.status(401).json({
      error: "Unauthorized",
      message: "Provide an Authorization: Bearer <token> header or an X-API-Key header.",
    });
  }

  // --- Input validation ---
  const parsed = RequestBodySchema.safeParse(req.body);
  if (!parsed.success) {
    return res.status(400).json({
      error: "Invalid request body",
      details: (parsed.error.issues ?? []).map((e) => ({
        path: (e.path ?? []).join("."),
        message: e.message,
      })),
    });
  }

  const issues: ChecklistIssueInput[] = Array.isArray(parsed.data)
    ? parsed.data
    : [parsed.data];

  try {
    const results = [];
    for (const issue of issues) {
      const [owner, repoName] = issue.repo.split("/");

      const title = `[${issue.severity.toUpperCase()}] ${issue.category}: ${issue.criterion}`;
      const body = formatIssueBody(issue);
      const labels = severityToLabels(issue.severity);

      const response = await fetchWithRetry(
        `https://api.github.com/repos/${owner}/${repoName}/issues`,
        {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            Accept: "application/vnd.github+json",
            "Content-Type": "application/json",
            "X-GitHub-Api-Version": "2022-11-28",
          },
          body: JSON.stringify({ title, body, labels }),
        }
      );

      if (!response.ok) {
        const errorText = await response.text();
        results.push({ checkId: issue.checkId, error: errorText, status: "failed" });
        continue;
      }

      const data = await response.json();
      results.push({
        checkId: issue.checkId,
        issueNumber: data.number,
        issueUrl: data.html_url,
        status: "created",
      });
    }

    return res.status(200).json({ results });
  } catch (error) {
    return res.status(500).json({
      error: error instanceof Error ? error.message : "Unknown error",
    });
  }
}

// Wrap with Upstash Redis sliding-window rate limit: 10 req / 60 s per IP
export default withRateLimit(handler, "github-create-issues", 10);
